default: &default
  adapter: mysql2
  database: globo_dot_com_test
  encoding: utf8
  username: root
  host: localhost

development:
  <<: *default
  username: root  
  password: 
      
production:
  <<: *default
